pyupio/safety

safety/cli.py, safety/safety.py
This can be used to ensure the requirements.txt doesn't allow
insecure versions.
This only works for lines which actually specify a version.
This is only tested with 'pkg>=1.2.3' like lines.
With small modifications this could be made to parse `pip freeze`
output on stdin.
Related Issue: https://github.com/pyupio/safety/issues/2
=> Add --read-requirements option to check the requirements.txt

safety/util.py
The setuptools documentation only documents the `project_name` attribute
for `Requirement` instances, so use it instead of `name`.
Closes #51
=> Prevent access to invalid requirement property

HISTORY.rst, safety/formatter.py
The code was correctly trapping `FileNotFoundError` for the case where `stty`
is not available on Windows.  However, on Python 2.7, the exception raised by
`subprocess.check_output()` is `WindowsError`, a subclass of `OSError`.
Fixes #65.
=> Fix get_terminal_size on Python 2.7 for Windows

safety/formatter.py
When call to stty fails for whatever reason we get ugly error
message that's not connected to `safety` itself.
Example:
```
$ safety check -r dependencies.txt
stty: 'standard input': Inappropriate ioctl for device
safety report
---
-> django, installed 1.9.10, affected >=1.9,<1.9.11, id 33075
-> django, installed 1.9.10, affected >=1.9,<1.9.11, id 33076
-> django, installed 1.9.10, affected >=1.9,<1.9.11, id 25734
-> django, installed 1.9.10, affected >=1.9,<1.9.13, id 33302
```
=> Suppress stderr output from stty when it fails

safety/safety.py, tests/test_safety.py
Addresses https://github.com/pyupio/safety/issues/80
Since the `found_ids` set specifically blocks this behavior, I don't know if this is wanted from the maintainers. I'm up for a discussion since this change is very helpful for me.
Signed-off-by: Kevin <kevin@stealsyour.pw>
=> Allows multiple versions of same library in check

safety/formatter.py
Fixes space fill so the table border always lines up correctly (see #101)
I'm not sure there's a more elegant way to do this with format strings :-/
=> variable-width space fill in SheetReport

safety/formatter.py
fix UnicodeDecodeError: 'ascii' codec can't decode byte
=> fix UnicodeDecodeError: 'ascii' codec #22

safety/formatter.py
This fixes a format type error some users are encountering after we moved to utf-8 encoding from [this commit](https://github.com/pyupio/safety/commit/1666851cf32a850e482ebb641c48f48fb8045c61).
Since some users require utf-8 encoding (the reason for the original change) I added a try catch which tries uft-8 encoding first, and if that fails falls back without it.
Issue discussion [here](https://github.com/pyupio/safety/issues/141)
=> Fix format type error from encode addition

safety/cli.py, setup.py
pip doesn't have a public API. This more-or-less inlines https://github.com/pypa/pip/blob/404838abcca467648180b358598c597b74d568c9/src/pip/_internal/utils/misc.py#L340-L394.
Fixes #90.
=> Remove API dependency on pip.

setup.py
Since few months pypi.org can deal properly with README at markdown format.
This pull requests specify to pypi to use markdown format.
=> Display properly README at markdown format on pypi

safety/safety.py
In safety.check(), when vulnerable packages are found, a second
'fetch_database' call is executed to get details. However, the 'proxy'
and 'cache' parameters are not passed to it. This patch fixes that.
=> Fix missing 'proxy' and 'cache' params in 'fetch_database' call

safety/util.py, tests/test_safety.py
=> resolve false negatives due to hashes in requirements file

safety/cli.py
When an invalid API Key is specified via the --key option, Safety displays an error message like:
Your API Key '12345-ABCDEFGH' is invalid. See https://goo.gl/O7Y1rS
However, when an invalid API Key is specified via the SAFETY_API_KEY environment variable, the error message doesn't include the key:
Your API Key '' is invalid. See https://goo.gl/O7Y1rS
This commit fixes the error message when the API Key is specified via the environment variable.
=> Fix error message for invalid API Key from environment variable

safety/util.py, tests/reqs_1.txt, tests/reqs_2.txt, tests/reqs_3.txt, tests/test_safety.py
This fixes Issue #132 to support using "-r" inside requirements.txt files.
There was already logic to handle these files, but there was a bug in the string parsing.
Tested on Ubuntu 18.04 with python 2.7.17 and 3.6.9.
```
$ cat tests/reqs_1.txt 
-r reqs_2.txt
$ cat tests/reqs_2.txt 
insecure-package==0.1.0
--requirement reqs_3.txt # with comment
$ cat tests/reqs_3.txt 
insecure-package==0.1.1
$ safety check -r tests/reqs_1.txt 
...
│ insecure-package           │ 0.1.0     │ <0.2.0                   │ 25853    │
│ insecure-package           │ 0.1.1     │ <0.2.0                   │ 25853    │
...
```
=> Fix -r inside requirements.txt files (#132)

setup.py
- Use 'io' package as a more reliable way of opening files
on Windows in Python 2.7
- Add python_requires, which helps pip determine if the
package is compatible with the user's installed version of Python.
- Cleanup and formatting of setup.py
=> Python Packaging improvements

safety/cli.py
That's how it used to look like:
```
--bare / --not-bare             Output vulnerable packages only. Useful in
combination with other tools.Default: --not-
bare
```
Note the `tools.Default:` part.
=> Adds missing space to `--bare` description

appveyor.py, appveyor.yml
We have some issues building MacOS binary through AppVeyor. This pull-request tries to use proper Python executable to get the build finishing with success.
=> MacOS AppVeyor Python Binary

safety/cli.py, safety/formatter.py, safety/safety.py, safety/util.py, tests/test_db/insecure_full.json, tests/test_db/licenses.json, tests/test_safety.py
This PR will allow Safety users visualize packages licenses using the new `license` sub command when available.
e.g `safety license --no-cache --key 84567236-123ef62a-1ff87072-191a95bb -r /local/test/requirements.txt`
=> Package license information on Safety.

safety/cli.py
A space seem to be missed in the help message.
```
--bare / --not-bare             Output vulnerable packages only. Useful in
combination with other tools.Default: --not-
bare
```
```
$ safety check --help
Usage: safety check [OPTIONS]
Options:
--key TEXT                      API Key for pyup.io's vulnerability
database. Can be set as SAFETY_API_KEY
environment variable. Default: empty
--db TEXT                       Path to a local vulnerability database.
Default: empty
--json / --no-json              Output vulnerabilities in JSON format.
Default: --no-json
--full-report / --short-report  Full reports include a security advisory (if
available). Default: --short-report
--bare / --not-bare             Output vulnerable packages only. Useful in
combination with other tools.Default: --not- …
```
=> Fix a missing space in help message of bare option

Dockerfilei386
Reference:
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
> For other items (files, directories) that do not require `ADD`’s
> tar auto-extraction capability, you should always use `COPY`.
=> Replace ADD with COPY instruction in Dockerfile

HISTORY.rst, README.md, safety/cli.py, safety/formatter.py, safety/safety.py, tests/test_safety.py
This will allow Safety-CLI users to have access when CVSS information is available on meta.
And only visible when using `--full-report`. Here some example (not a real vuln):
=> Provide CVSS information when available.

README.md, safety/cli.py, safety/output_utils.py, safety/safety.py, safety/util.py, tests/test_cli.py, tests/test_output_utils.py, tests/test_safety.py
This PR removes the heavy use of the click context; now, Safety can be used in non-CLI environments.
Other fixes:
- Documentation improvement in the help section for each command
- Fixed issue in the review command
=> Safety support as a package

safety/util.py
Prevents "fatal: not a git repository (or any of the parent directories): .git" in cases where safety is ran outside a git repository.
=> Eat stderr messages from git commands.

safety/cli.py, safety/output_utils.py, safety/safety.py, safety/util.py
Now Safety reads Pipenv and Poetry lock files, plus other files supported by dparse.
=> Using dparse to read requirements and fixes for custom integrations

safety/safety.py
Remove the imports related to `LegacyVersion`, which was used in the past, but isn't required now.
=> Remove the LegacyVersion import

.github/workflows/build.yml, .github/workflows/main.yml, .github/workflows/test-insecure.yml, .github/workflows/test-secure.yml, setup.cfg
- Packaging now is pinned to the maximum version compatible; this is `packaging>=21.0,<22.0`.
- Pinned the CI actions to the runner image with Python 3.6 support.
=> Pin packaging to a compatible version

.github/workflows/build.yml
We'll use the `image-builds` branch to push updates on the docker image.
=> Build docker image on image-builds push

setup.cfg, test_requirements.txt
We don't need `jwt`, and `authlib` should be unpinned.
=> perf: unpin authlib and remove jwt

safety/auth/cli.py, safety/auth/main.py, safety/auth/server.py, test_requirements.txt, tests/auth/test_cli.py, tests/auth/test_main.py, tests/test_cli.py, tests/test_safety.py, tox.ini
Introduce an additional flag to enable an alternative login mechanism that bypasses the need for a local web server.
=> feat: add headless auth

setup.cfg, test_requirements.txt, tests/test_cli.py, tests/test_safety.py
Support for multiple Pydantic versions and upgrade safety_schemas version.
=> fix: support pydantic2 by using safety_schemas 0.0.2

safety.spec, safety/__main__.py
Relative imports on `cli.py` are breaking the binaries; this changes the target scripts and fixes this issue.
=> fix: update pyinstaller target

safety/auth/cli_utils.py, safety/auth/models.py, safety/cli.py, safety/safety.py, safety/scan/decorators.py, safety/scan/finder/handlers.py, safety/scan/validators.py, tests/scan/test_file_handlers.py
Add an env var for offline databases.
=> feat: add SAFETY_DB_DIR env var to the scan command

MANIFEST.in
Now, it includes all the files/dirs under the `templates` folder.
=> fix: include all templates in the manifest

MANIFEST.in
This includes the scan folder inside the `safety/templates`
=> fix: include scan template in the build

safety/scan/ecosystems/python/main.py, tests/scan/ecosystems/python/test_main.py
Enhanced exit code handling for scenarios where fail-on unknown/none labels are used and vulnerabilities lack the severity value.
=> fix: fail on none severities

safety/constants.py
As mentioned in #487, safety often times out for us. Increasing the timeout should fix it for us (and anyone else with slower internet connections, proxies etc).
=> Increase request timeout to 30 seconds

safety/errors.py, tests/test_cli.py, tests/test_safety.py
https://linear.app/pyup/issue/SFTY-657/update-invalid-api-key-url
This PR changes updates all references of the URL https://bit.ly/3OY2wEI to:
https://docs.safetycli.com/safety-docs/support/invalid-api-key-error
=> Update URLs, Lint

safety/constants.py
Adding support for `REQUEST_TIMEOUT` to be set via the env var `SAFETY_REQUEST_TIMEOUT`
https://linear.app/pyup/issue/SFTY-913/safety-cli-timeout-env-var
=> REQUEST_TIMEOUT Env Var

safety/safety.py, safety/scan/ecosystems/python/main.py, setup.cfg, test_requirements.txt, tests/test_safety.py
- Added file lock handling for get_from_cache=None
- Updated to filelock==3.12.2
- Ensured the cache directory exists
- Updated write_cache and corresponding tests
=> fix(cache): handle get_from_cache=None and ensure directory exists

safety/cli.py, tests/test_cli.py
- Fix --debug flag functionality
- Add tests using runner.invoke
- Fix and modify fetch_database function
- Ensure all tests pass with appropriate patchings
=> fix(debug): fix --debug flag and associated tests

.github/workflows/issue_responder.yml
**Description**
This pull request adds a new GitHub Action that automatically responds to new issues created in the repository. The action is configured to trigger whenever a new issue is opened and posts a predefined comment thanking the user and acknowledging the issue.
**Changes**
- Added a new GitHub Action workflow file .github/workflows/issue-responder.yml.
- Configured the workflow to trigger on the issues event with the type opened.
- The action uses actions/github-script@v7 to post a comment on the newly created issue.
- The comment includes the title and body of the issue and a thank-you message.
- The comment will appear as if posted by the account associated with the GITHUB_TOKEN.
- This setup ensures a single response per new issue.
=> feat: add GitHub Action to automatically respond to new issues

.vscode/launch.json, safety/cli.py, safety/scan/constants.py, safety/scan/decorators.py, safety/scan/validators.py
Previously use of an API Key required "--stage cicd" to function, this has be removed.
This is **NOT A BREAKING CHANGE**, users who have "--stage cicd" in their automations will still complete their scans.
=> feat: api keys now work without specifying the env

safety/scan/command.py, tests/scan/test_command.py
This PR introduces the following enhancements to the safety scan command:
**1. CVE Details in Detailed JSON Output**
* Added a new section, cve_details, to the JSON output when --detailed-output  is enabled and output format is specified to json.
* The cve_details section provides comprehensive information about CVEs, including affected packages, severity, CVE IDs, and advisory links.
**2. Single-Key Filtering for JSON Output**
* Implemented the ability to filter the JSON output by a single top-level key using the --filter option.
* Users can now focus on specific sections of the report, such as meta or cve_details, simplifying the output for targeted use cases.
**3. Improved Report Processing**
* Encapsulated the filtering logic into a reusable helper function, filter_json_keys, …
=> Add CVE Details and Single-Key Filtering for JSON Output in safety scan

.github/workflows/bump.yml, .github/workflows/cd.yml, .github/workflows/reusable-build.yml
Improvements to handling bump and release.
=> ci: improve beta bump and release handling

.github/workflows/cd.yml
Assets with the same name cause issues creating the GitHub release.
=> ci: rename assets on release to avoid conflicts

safety/auth/utils.py, safety/errors.py, safety/scan/render.py, tests/auth/test_auth_utils.py
On server errors with JSON responses, the CLI was using response.text instead of response.json() to get the detail, causing string formatting conflicts. Now, it properly parses JSON responses before error handling.
=> fix: no proper handling of JSON server errors

pyproject.toml, safety/tool/utils.py
Replaces dependency of `python-levenshtein` with `nltk` package.
=> chore: Replaced edit distance with NLTK package

LICENSES/NOTICE.md, refresh_notice.py
With this utility you can refresh the NOTICE.md for all the dependencies required by Safety
Example:
```
uv run --isolated --with safety==3.3.0 python refresh_notice.py
```
=> chore: add a refresh notice utility script and update the NOTICE file

README.md
=> chore: use the new ci workflow badge

.github/workflows/ci.yml
args now should be passed to hatch correctly.
=> ci: add proper parsing for hatch lint

safety/util.py, tests/test_util.py
When only an API Key is used, the event bus fails; this solves that issue.
=> fix: prevent AttributeError on event bus start when only API Key is used

safety/cli.py
Add back the missing patch removed by lint.
=> fix: patch asyncio to avoid Windows exception on legacy Python versions

safety/init/command.py, safety/init/constants.py, safety/init/render.py
The output was too verbose and instantaneous, so we introduced a pause so the user had time to read what Safety CLI set up in their system.
=> fix: instantaneous init output

safety/init/command.py, safety/init/constants.py
Once the safety firewall is set up for the first time, users must either run a source command or restart their terminal to activate it. We failed to include these instructions in the UI copy, causing user confusion when the feature didn't work immediately after running the safety init command.
=> fix: add missing instructions for terminal activation after safety init

safety/tool/uv/command.py
Sometimes, the args can be empty, and I didn't consider it before.
=> fix: uv index out of range issue

safety/tool/uv/main.py, tests/tool/uv/test_main.py
index is the only aot in the uv project configuration
=> fix: usage of aot instead of tables for uv project

safety/cli_util.py
Users need the uninstall command always available.
=> fix: missing uninstall option when feature flag is disabled

pyproject.toml
`click 8.2.0` broke multiple things; this constraint will prevent new users from falling into the errors.
=> fix: click version constraint

.github/workflows/ci.yml
Tests aren't running on schedule CI, this PR should fix it.
=> ci: make sure tests run if lint is skipped

safety/scan/init_scan.py
Removes the now redundant logic that set the branch in the query parameter part of URL.
=> bug: preventing the branch name to be included in the codebase url

.github/workflows/ci.yml
I made a mistake on the needs the last time. Obviously, `needs` don't allow GitHub expressions, but aha! I missed that one.
=> ci: avoid lint on schedule but keep matrix/tests

safety/tool/auth.py, safety/tool/pip/main.py, safety/tool/uv/command.py, tests/tool/test_auth.py, tests/tool/uv/test_uv_command.py
This adds the index credential env vars for uv commands.
=> fix: add missing uv index env var for auth

safety/encoding.py, safety/scan/ecosystems/target.py, safety/scan/main.py, safety/tool/pip/command.py, safety/tool/pip/main.py, tests/test_encoding.py
This prevents the CLI from crashing when users use UTF-16 and UTF-8-SIG encodings. UTF-16 is mostly used on Windows
For other encodings, Safety CLI will fail.
=> fix: encoding issues when reading user UTF-16 and UTF-8-SIG encoded files

safety/scan/command.py
The `logger.warn()` method is deprecated since Python2.7 and replaced with `logger.warning()`. It leads to those warnings:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
This small PR resolves those warnings.
=> fix: resolve logger warnings

safety/codebase/constants.py
Some fixes on help text for the `--link-to` option.
=> fix: codebase init --link-to help text

safety/codebase/command.py, safety/init/main.py, safety/scan/decorators.py
The scan command previously prompted users to provide a codebase name when scanning a project that didn't exist in an interactive environment. This functionality was accidentally removed during a refactor of the codebase init command. This fix restores the prompt behavior by adding a prompt_for_name parameter to the verify_project function and ensuring it's enabled when called from the scan command, maintaining the expected user experience for new codebase creation.
=> fix: restore missing codebase name prompt in scan command

safety/auth/server.py, safety/console.py, safety/emoji.py, safety/init/command.py, safety/init/constants.py, safety/init/main.py, safety/init/render.py, safety/scan/command.py, safety/scan/fun_mode/celebration_effects.py, safety/scan/fun_mode/easter_eggs.py, safety/scan/render.py
=> fix: issues with encoding in all the outputs

safety/alerts/__init__.py, safety/alerts/github.py, safety/alerts/requirements.py, safety/alerts/utils.py, safety/meta.py, safety/safety.py, tests/test_meta.py, tests/test_user_agent_integration.py
All network requests from the Safety CLI now include a standardized user-agent header in the format: safety-cli/{version} ({os} {arch}; Python/{python_version}). This change enables Safety to distinguish requests coming from the CLI versus other sources when accessing the Safety Vulnerability Database (safety-db), providing better visibility into how the database is being consumed. The user-agent is centrally managed through the get_meta_http_headers() function to ensure consistency across all HTTP clients (requests and httpx).
=> fix: set custom user-agent header to all HTTP requests

pyproject.toml
Loosened version pinning to allow more flexibility in dependency resolution. See #721 for detailed rationale.
=> chore: relax filelock version constraints

pyproject.toml
Loosened version pinning to allow more flexibility in dependency resolution. See #721 for detailed rationale.
=> chore: relax psutil version constraints

safety/cli.py
Replaces https://github.com/pyupio/safety/pull/779 with corrected commit-message convention.
Addresses https://github.com/pyupio/safety/issues/778, where accessing `typer.rich_utils` as an attribute is no longer valid for `typer>=0.17.0` because it now lazily imports `rich_utils`: https://github.com/fastapi/typer/discussions/1285
- [ x] Bug fix
Fixes https://github.com/pyupio/safety/issues/778
Addresses https://github.com/fastapi/typer/discussions/1285
- [? ] No tests required
```
(my_safety_env) My-MacBook-Pro:safety KalebCoberly$ pip install -e .
...
Installing collected packages: safety
Attempting uninstall: safety
Found existing installation: safety 3.6.0
Uninstalling safety-3.6.0:
Successfully uninstalled safety-3.6.0
Successfully installed safety-3.6.1b0
(my_safety_env) …
```
=> Fix/kaleb coberly/import rich utils

.github/workflows/pr-comment.yml
This clarifies the artifacts' origin and fixes the issue to get the PR number via the GraphQL API.
=> ci: resolve PR number via graphql API and update artifacts message

pyproject.toml
Start to use our own project index.
=> ci: add firewall index to the project setup

pyproject.toml
The new schema supports package locations and tool absolute paths.
=> chore: use the latest safety_schemas version
