pyupio/safety

safety/cli.py
safety/formatter.py
tests/test_safety.py

I needed json output, to more easily parse/report on the results. Default behavior should be identical to how it was before.
Happy to modify/improve this, if it's a feature you're open to adding!

Allow setting output format, add json output

---

safety/formatter.py

See `checked 8 packages, using default DB` under `REPORT`
Before:
```console
sven:~/Dropbox/fun/safety> safety check -r requirements_dev.txt
╒══════════════════════════════════════════════════════════════════════════════╕
│                                                                              │
│                               /$$$$$$            /$$                         │
│                              /$$__  $$          | $$                         │
│           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           │
│          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           │
│         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           │
│          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           │
│ …
```

add space to checks formatting

---

safety/util.py

Logging filename on unpinned requirement warning

---

safety/cli.py
safety/safety.py
tests/test_safety.py

Amended PR from https://github.com/pyupio/safety/pull/161/

Add Proxy Support

---

README.md

added gitlab-ci.yml instructions to README CI help

---

safety/formatters/json.py
safety/formatters/screen.py
safety/formatters/text.py
safety/output_utils.py
safety/safety.py

This improves the screen/text output.

Improving grammar and formatting in the whole code

---

MANIFEST.in
safety/cli.py
safety/constants.py
safety/formatters/json.py
safety/formatters/screen.py
safety/formatters/text.py
safety/output_utils.py
safety/safety-policy-template.yml
safety/safety.py
safety/util.py
tests/test_cli.py
tests/test_output_utils.py
tests/test_policy_file/default_policy_file.yml
tests/test_policy_file/default_policy_file_using_invalid_keyword.yml
tests/test_policy_file/default_policy_file_using_invalid_typo_keyword.yml

This PR adds two new policy commands, increases the coverage, and makes some fixes in the whole code.

Adding new policy commands, adding some tests and last fixes

---

safety/cli.py
safety/output_utils.py
tests/test_cli.py

Also, this adds some fixes to the generate command.

Fixing the brief report and Generate command

---

safety/cli.py
safety/errors.py
safety/safety.py
safety/util.py

General bug fixes over the Safety 2.0 version.

Improving error messages, fixing license command and fixing proxy issue

---

safety/cli.py
safety/output_utils.py
safety/safety.py
safety/util.py

Adds the ability for scan results to be sent and logged on pyup.io

Safety POST for pyup.io

---

safety/output_utils.py
safety/safety.py
safety/util.py

- Proper validation for SAFETY_COLOR env var.
- Handling cases when CVE ids are None.

Common fixes for next release

---

safety/models.py
safety/output_utils.py
safety/safety.py
safety/util.py
setup.cfg
tests/formatters/test_json.py
tests/resources.py
tests/test_output_utils.py
tests/test_safety.py

This PR fixes the issue with newer packaging versions by properly handling non-pinned versions in different contexts.

Fixes to allow newer packaging version.

---

README.md

Just wanted to highlight that we are hiring in our README.md
- Added a note at the top with a link to our Workable Careers page.
- Added a link at the bottom to the same page.

Added note on hiring and careers page link

---

safety/auth/cli.py
safety/auth/cli_utils.py
safety/auth/constants.py
safety/auth/main.py
safety/auth/models.py
safety/auth/utils.py

Minor fix for handling multiple email verification claims. Later, we'll migrate to use only one.

fix: use available email verification claims

---

CODE_OF_CONDUCT.md

**Summary:**
This PR introduces a Code of Conduct document to the Safety CLI project. The document outlines the standards for behavior expected from all contributors and maintainers, promoting a welcoming and harassment-free environment.
**Why this is important:**
**- Fosters Inclusivity:** Establishes clear guidelines to ensure a welcoming and inclusive environment for all participants, regardless of background.
**- Sets Behavioural Standards:** Clearly defines acceptable and unacceptable behaviours, helping to prevent harassment, discrimination, and other negative actions.
**- Guides Conflict Resolution:** Provides a framework for addressing conflicts and resolving issues in a constructive manner.
**- Encourages Professionalism:** Reinforces the expectation of professional behavior in …

Add Code of Conduct Document

---

safety/auth/utils.py
tests/auth/test_cli.py

feat(utils.py): remove email verification

---

safety/scan/command.py
safety/scan/fun_mode/celebration_effects.py
safety/scan/fun_mode/easter_eggs.py

**Pull Request Description**
This PR introduces Fun Mode, an exciting way to celebrate successful vulnerability scans in SafetyCLI. Fun Mode enhances user engagement by displaying a variety of celebratory effects when no vulnerabilities are detected.
**Key Changes**
1. New `run_easter_egg(console, exit_code)`:
* This function runs a celebratory animation or message based on the SAFETY_FUN_MODE environment variable.
2. Effects Library (`celebration_effects.py`):
* Added a dedicated helper file containing various celebration effects:
* Confetti: A burst of colorful confetti.
* Trophy: A golden trophy with sparkles.
* Balloons: Popping balloons in the console.
* Victory Parade: A parade of celebratory emojis.
* Confetti Rain: A vibrant, cascading confetti animation.
* Fireworks: A fireworks …

Add Fun Mode to Celebrate Vulnerability-Free Scans

---

setup.cfg
test_requirements.txt

Sets a minimum version for typer package and update the setup.cfg
#563

chore/update setup.cfg and typer minimum version

---

safety/scan/ecosystems/python/main.py
setup.cfg

Fix for NoneType is not iterable

---

.github/workflows/contributor.yml

Checking if the PR is from a fork is sufficient to determine if these test can run or not.

feat/ add dev team membership for contributor action

---

.github/workflows/bump.yml
pyproject.toml

Bumps version and changelog via workflow dispatch.

ci: add bump workflow

---

.github/workflows/bump.yml

Fetch the history so Bump has enough context.

ci: fetch tags and history on bump workflow

---

.github/workflows/build.yml

Add the option to publish beta images and also be more flexible with the latest tag.

chore: update the docker build workflow

---

safety/init/command.py
safety/tool/constants.py
safety/tool/main.py
safety/tool/pip.py
safety/tool/poetry.py
safety/tool/utils.py

Populates the `project-id` query parameter with the project id.

Configuring the repository URL using project id

---

.github/scripts/matrix.py
.github/workflows/ci.yml
pyproject.toml

Basic type checking, commit verification, and the possibility of targeting/testing specific versions.

ci: add commit, style and type checks plus experimental dependency targets

---

.github/workflows/ci.yml

This addresses the multiline issue of changed files.

ci: fix changed files issue

---

safety/init/command.py
safety/init/main.py
safety/tool/constants.py
safety/tool/main.py
safety/tool/pip.py
safety/tool/poetry.py
safety/tool/utils.py
tests/init/test_init_main.py

Updates the Firewall URL to include the organization slug.

Generating organization slug

---

safety/events/event_bus/utils.py
safety/tool/pip.py

Bugfixing broken API Key usage.

fix: handling API Key usage and missing token

---

safety/asyncio_patch.py
safety/auth/cli.py
safety/auth/server.py
safety/cli.py
safety/init/command.py
safety/init/constants.py
safety/init/main.py
safety/init/render.py
safety/scan/command.py
safety/scan/finder/file_finder.py
safety/scan/init_scan.py
safety/scan/render.py
safety/tool/interceptors/unix.py
safety/tool/main.py
safety/tool/pip.py
safety/tool/poetry.py
safety/tool/tool_inspector.py
safety/tool/utils.py
tests/scan/test_file_finder.py
tests/scan/test_render.py
tests/test_cli.py

This revamped the init following the beta feedback and new specs.

chore: modify init with the UI feedback

---

safety/formatters/json.py
safety/formatters/schemas/__init__.py
safety/formatters/schemas/zero_five.py

Handles the case of marshmallow 4.*
This PR will fix #711, and it will be shipped in Safety CLI `3.4.0`

fix: add compatibility for marshmallow 4.*

---

safety/init/command.py
safety/init/constants.py

Fixes bugs on the init scan used by the init command.

fix: init scan none links

---

safety/auth/utils.py
safety/events/handlers/common.py
safety/events/utils/creation.py
safety/meta.py

This is required to control feature flag behavior for features that require a minimum CLI version.

feat: add meta client headers to all requests

---

LICENSES/NOTICE.md

Just housekeeping to make sure the list is updated.

chore: update dependencies licenses list

---

safety/init/constants.py
safety/init/main.py
safety/tool/main.py
safety/tool/utils.py
safety/tool/uv/main.py
tests/tool/uv/test_main.py

This fix the issue between projects and system configuration, now uv system setup is executed and poetry project setup was moved to codebase setup instead.

fix: tool issues on uv and poetry setup

---

safety/cli_util.py
safety/tool/__init__.py
safety/tool/base.py
safety/tool/definitions.py
safety/tool/factory.py
safety/tool/interceptors/base.py
safety/tool/interceptors/unix.py
safety/tool/pip/command.py
safety/tool/poetry/command.py
safety/tool/uv/command.py
tests/tool/interceptors/test_unix.py

Fixes bugs in parsing and exit codes.

fix: tool parsing and tool exit codes

---

.safety-project.ini
safety/tool/pip/command.py

Expands on the ability to report on the installed packages to detect the packages that were affected by the specific tool command. This change will now allow to support installation done over configuration/project files like `requirements.txt` and `pyproject.toml`.

Added resolution of installed packages

---

safety/asyncio_patch.py
safety/tool/tool_inspector.py

Fix RuntimeError when garbage collector tries to clean up subprocess transports after event loop closure. Affects multiple Python versions (3.8+) on both Windows and Unix platforms. Added patches to safely handle 'Event loop is closed' errors in BaseSubprocessTransport.__del__, _ProactorBasePipeTransport.__del__ and others.

fix: suppress event loop errors during subprocess transport cleanup

---

safety/tool/pip/command.py

Makes change to rendering of the warning messages.
- [] Bug fix

chore:improved rendering of the warning messages

---

safety/tool/pip/command.py

Correctly passed version information when the version is not a tuple, and unpacks any tuples on updates.

bug: fix the version information passing

---

safety/events/handlers/common.py

This adds flexibility for the timeout setting in the events endpoint.

feat: add 'SAFETY_REQUEST_TIMEOUT_EVENTS' so users can use a custom timeout

---

safety/tool/base.py
safety/tool/poetry/command.py
safety/tool/poetry/constants.py
safety/tool/poetry/main.py
safety/tool/poetry/parser.py

Now we auto-add the Safety source, and we have also fixed the issues parsing Poetry projects.

fix: poetry error on source and parsing pyproject.toml

---

CHANGELOG.md

Just add a note to the changelog to explain that the generation is automated.

chore: update CHANGELOG.md with note

---

safety/auth/utils.py
safety/safety.py
tests/test_safety.py

Our legacy code uses a session class that doesn't have a proper retry with exp-backoff, by adding this, we'll improve the reliability.

chore: add retries to legacy requests

---

.github/scripts/matrix.py
pyproject.toml

This is the first step to remove the constraint on Pydantic.

chore: upgrade safety_schemas version

---

.github/workflows/pr-comment.yml

ci: add bot access to the comment workflow

---

.github/workflows/bump.yml
.github/workflows/ci.yml
.github/workflows/reusable-build.yml
pyproject.toml
safety/events/utils/emission.py
safety/models/tools.py
safety/tool/base.py
safety/tool/environment_diff.py
safety/tool/resolver.py
tests/events/utils/test_emission.py
tests/tool/test_environment_diff.py
tests/tool/test_resolver.py

This implements the changes to collect the package and tool location.

fix: allow passing package and tool location
